services:
  inventory-hub:
    container_name: inventory_hub
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      # 1. App Code
      - ./:/app
      
      # 2. Config File (Parent Dir)
      - ../config.json:/config.json
      
      # 3. THE MAGIC VARIABLE ðŸŽ©
      # This tells Docker: "Look in the .env file to find out where this folder is."
      - "${LABEL_OUTPUT_PATH}:/output"

    environment:
      - PYTHONUNBUFFERED=1