services:
  inventory-hub:
    container_name: inventory_hub
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      # Map the WHOLE current directory to /app
      # This lets Python see app.py, logic.py, state.py, etc.
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1